# Generated by Django 4.1.7 on 2023-06-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(blank=True, choices=[('simple', 'Простой'), ('VIP', 'ВИП')], default='simple', max_length=255),
        ),
    ]
