# Generated by Django 4.1.7 on 2023-02-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
