# Generated by Django 4.1.7 on 2023-06-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_files', '0003_alter_files_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='date',
        ),
        migrations.AddField(
            model_name='files',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
