# Generated by Django 4.1.7 on 2023-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_files', '0004_remove_files_date_files_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
