# Generated by Django 4.1.7 on 2023-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_files', '0006_files_cover_files_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
